configs:
  credentialTemplates:
    github-repos:
      url: https://github.com/RSO-2024-Group-12
      githubAppID: "2600428"
      githubAppInstallationID: "102782152"
      githubAppEnterpriseBaseUrl: https://github.com/organizations/RSO-2024-Group-12/
      githubAppPrivateKey: FILL ME IN

  repositories:
    ghcr-helm:
      url: ghcr.io/rso-2024-group-12
      type: helm
      enableOCI: "true"
      username: argo-cd # can be anything tbh just password matters
      password: FILL IN