# Access to organization resources is done with a GitHub App that was created for this purpose

githubAppInfo:
  id: "2600428"
  installationId: "102782152"
  enterpriseBaseUrl: https://github.com/organizations/RSO-2024-Group-12/
  privateKey:

credentials:
  github-repos:
    url: https://github.com/RSO-2024-Group-12
    type: github
  ghcr-helm:
    url: ghcr.io/rso-2024-group-12
    type: helm
    enable-oci: "true"

# parent-argo-cd:
  # configs:
    # Or should i create them myself?
    # credentialTemplates:
    #   github-repos:
    #     url: https://github.com/RSO-2024-Group-12
    #     githubAppID: "2600428"
    #     githubAppInstallationID: "102782152"
    #     githubAppEnterpriseBaseUrl: https://github.com/organizations/RSO-2024-Group-12/
    #     # Use the private key generated when creating the GitHub App
    #     # Override this value with help from generated values-private.yaml
    #     githubAppPrivateKey: FILL ME IN
    #   ghcr-helm:
    #     url: ghcr.io/rso-2024-group-12
    #     type: helm
    #     enable-oci: true
    #     githubAppID: "2600428"
    #     githubAppInstallationID: "102782152"
    #     githubAppEnterpriseBaseUrl: https://github.com/organizations/RSO-2024-Group-12/
    #     # Use the private key generated when creating the GitHub App
    #     # Override this value with help from generated values-private.yaml
    #     githubAppPrivateKey: FILL ME IN
