apiVersion: v2
name: infra-components
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: cloudnative-pg
    version: 0.26.0
    repository: https://cloudnative-pg.github.io/charts
    condition: postgresql.enabled
  - name: strimzi-kafka-operator
    version: 0.48.0
    repository: https://strimzi.io/charts/
    condition: kafka.enabled
