# Default values for keycloak.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

dbInit:
  db:
    user: keycloak_user
    password:
    database: keycloak_db
    schema: keycloak_schema
    hostAddress:
    hostPort:
  pgAdminUserSecret:
    secretName:
    secretKey: