apiVersion: v1
kind: Secret
metadata:
  name: nakupify-db-nakupify-secret
  namespace: default
type: kubernetes.io/basic-auth
stringData:
  username: "nakupify"
  password: "nakupify"
---
apiVersion: v1
kind: Secret
metadata:
  name: nakupify-db-postgres-secret
  namespace: default
type: kubernetes.io/basic-auth
stringData:
  username: "postgres"
  password: "postgres"