apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nakupify-db
  namespace: default
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  bootstrap:
    initdb:
      database: nakupify
      secret:
        name: nakupify-db-nakupify-secret
  enableSuperuserAccess: true
  superuserSecret:
    name: nakupify-db-postgres-secret
  storage:
    size: 5Gi
    storageClass: managed
  postgresql:
    parameters:
      shared_buffers: "256MB"