db:
  # Name of the role assoicatited with the database
  user:
  
  # Password for the database user, if empty, generates a random one
  password:

  # Name of the created database or schema in database
  database:

  # Created initial schema in the database
  schema:
  
  # Address of postgres database
  hostAddress:

  # Port of postgres database
  hostPort: 

# Postgres image to use for db-init job, also can be used to specify repo
pgImage: postgres

# Postgres image tag to use for db-init job
pgImageTag: "17-alpine"

# Admin user secret to use to connect to Postgres and create the database and user
pgAdminUserSecret:
  # Name of the secret
  secretName: 
  # Key in the secret that contains the postgres connection URI
  secretKey: 